gitpatron/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',

    url(r'^$', 'app.views.index',name='site_landing'),
    url(r'^oauth_redirect/$', 'app.views.oauth_redirect',name='oauth_redirect'),

    url(r'^index.html', 'app.views.index',name='site_landing'),
    url(r'^home.html', 'app.views.home', name='patron_home'),
    url(r'^logout.html', 'app.views.logout_user', name='logout'),

    url(r'^login.html', 'app.views.login_user', name='login'),

    #github repos for the user
    url(r'^ghrepos.html', 'app.views.github_repos', name='github_repos'),

    #these are the published repos
    url(r'^public/repos.html', 'app.views.public_repos',name='public_repos'),

    url(r'^claimed.html', 'app.views.claimed',name='user_claimed'),
    url(r'^about.html', 'app.views.about_gitpatron',name='about_gitpatron'),
    url(r'^attribution.html', 'app.views.attribution',name='attribution'),
    url(r'^moderator.html', 'app.views.moderator', name='moderator'),

    url(r'^wallet_wf_ajax/([-\w]+)/$', 'app.views.wallet_wf_ajax', name='wallet_wf_ajax'),

    url(r'^revoke_wallet/$', 'app.views.revoke_wallet', name='revoke_wallet'),


    url(r'^repo/([-\w]+)/([-\w]+)/$', 'app.views.repo', name='repo'),

    #json
    url(r'^repo/([-\w]+)/([-\w]+)/chart.json$',
        'app.views.repo_chart_json', name='repo_chart_json'),




    #publish_repo_ajax
    url(r'^publish_repo_ajax/([-\w]+)/([-\w]+)/$',
        'app.views.publish_repo_ajax',name='publish_repo_ajax'),

    #sync_issues_ajax
    url(r'^sync_issues_ajax/([-\w]+)/([-\w]+)/$',
        'app.views.sync_issues_ajax',name='sync_issues_ajax'),

    #monetize_issue_ajax
    url(r'^monetize_issue_ajax/([\w]+)/$',
        'app.views.monetize_issue_ajax',name='monetize_issue_ajax'),

    #monetize_issue_ajax
    url(r'^monetize_repo_ajax/([\w]+)/$',
        'app.views.monetize_repo_ajax',name='monetize_repo_ajax'),


    #claim issue
    url(r'^claim_issue_ajax/([\w]+)/$',
        'app.views.claim_issue_ajax',name='claim_issue_ajax'),

    #fix issue
    url(r'^fix_issue_ajax/([\w]+)/$',
        'app.views.fix_issue_ajax',name='fix_issue_ajax'),

    #monetize fix issue
    url(r'^monetize_fix_ajax/([\w]+)/([\w]+)/$',
        'app.views.monetize_fix_ajax',name='monetize_fix_ajax'),

    #fix
    url(r'^claimed/([\w]+)/$',
        'app.views.claimed_issue',name='claimed_issue'),

    #watch a repo
    url(r'^watch_repo_ajax/([\w]+)/$',
            'app.views.watch_repo_ajax',name='watch_repo_ajax'),

    #issue
    url(r'^issue/([-\w]+)/([-\w]+)/([-\w]+)/$',
        'app.views.issue',name='issue'),

    #json
    url(r'^issue/([-\w]+)/([-\w]+)/([-\w]+)/chart.json$',
        'app.views.issue_chart_json',name='issue_chart_json'),

    #patron
    url(r'^patron/([-\w]+)/$',
        'app.views.patron',name='patron'),

    # #fix form
    # url(r'^fix_form_ajax/([-\w]+)/([-\w]+)/([-\w]+)/$',
    #     'app.views.fix_form_ajax',name='fix_form_ajax'),


    #repo owner view patronage
    url(r'^patronage.html',
            'app.views.patronage',name='patronage'),

    #committer payments
    url(r'^payments.html',
            'app.views.payments',name='payments'),

    #associate pull
    url(r'^pull_mapping_ajax/([-\w]+)/([-\w]+)/([-\w]+)/$',
        'app.views.pull_mapping_ajax',name='pull_mapping_ajax'),

    #coin oauth
    url(r'^cbauthredirect.html', 'app.views.cb_auth_redirect',name='cb_auth_redirect'),
    #coing oauth callback
    url(r'^coin_callback.html', 'app.views.coinbase_callback',name='coinbase_callback'),
    
    #coin calls this is when an user pays coin
    url(r'^cbcallback/([\w]+)/$', 'app.views.cbcallback',name='cbcallback'),

    #the activation callback
    url(r'^activate_callback/$', 'app.views.activate_callback',name='activate_callback'),

    #coin result pages
    url(r'^coin_success.html', 'app.views.coin_success',name='coin_success'),
    url(r'^coin_cancel.html', 'app.views.coin_cancel',name='coin_cancel'),
    url(r'^coin_info.html', 'app.views.coin_info',name='coin_info'),

    url(r'^settings.html', 'app.views.patron_settings',name='patron_settings'),

    #sharable widgets
    #issue iframe javascript
    url(r'^widget/issue.js$', 'app.views.issue_widget_js', name='issue_widget_js'),
    #issue iframe contents
    url(r'^widget/issue/([\w]+)/$', 'app.views.issue_widget', name='issue_widget'),
    #popup contents
    url(r'^popup/issue/([\w]+)/$', 'app.views.issue_popup', name='issue_popup'),



    #admin
    url(r'^admin/', include(admin.site.urls)),
)

app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.exceptions import PermissionDenied
from django.shortcuts import get_object_or_404

import re

reply_re = re.compile("^@(\w+)")

#from django.core.management import call_command
#call_command('syncdb', interactive=True)
#call_command('migrate', interactive=True)

class Patron(models.Model):
    user = models.ForeignKey(User)
    name = models.CharField(max_length=250, unique=False, blank=True,  null=True)
    img = models.URLField(default="", verbose_name='Image URL', blank=True, null=True)
    bio = models.TextField( default="", verbose_name='Patron Bio', blank=True,  null=True)

    # "login": "claytantor",
    github_login = models.CharField(max_length=250, unique=False)

    #   "id": 407854,
    github_id = models.BigIntegerField(unique=True, blank=True,  null=True)

    #   "avatar_url": "https://avatars.githubusercontent.com/u/407854?",
    github_avatar_url = models.CharField(max_length=250, unique=False, blank=True, null=True)

    #   "gravatar_id": "c88d7ef134a9779657d7d63257b5f725",
    #   "url": "https://api.github.com/users/claytantor",

    #   "html_url": "https://github.com/claytantor",
    #   "followers_url": "https://api.github.com/users/claytantor/followers",
    #   "following_url": "https://api.github.com/users/claytantor/following{/other_user}",
    #   "gists_url": "https://api.github.com/users/claytantor/gists{/gist_id}",
    #   "starred_url": "https://api.github.com/users/claytantor/starred{/owner}{/repo}",
    #   "subscriptions_url": "https://api.github.com/users/claytantor/subscriptions",
    #   "organizations_url": "https://api.github.com/users/claytantor/orgs",
    #   "repos_url": "https://api.github.com/users/claytantor/repos",
    #   "events_url": "https://api.github.com/users/claytantor/events{/privacy}",
    #   "received_events_url": "https://api.github.com/users/claytantor/received_events",

    #   "type": "User",
    github_type = models.CharField(max_length=16, unique=False, blank=True,  null=True, default='User')

    github_access_token = models.CharField(max_length=64, unique=False)

    coinbase_access_token = models.CharField(max_length=250, unique=False, blank=True,  null=True)

    coinbase_refresh_token = models.CharField(max_length=250, unique=False, blank=True,  null=True)

    coinbase_callback_secret = models.CharField(max_length=128, unique=False, blank=True,  null=True)

    #is_account_created
    account_created = models.NullBooleanField(default=False,  blank=True,  null=True)

    #wallet_address
    wallet_address = models.CharField(max_length=64, unique=False, blank=True,  null=True)

    #has_donated
    has_donated = models.NullBooleanField(default=False, null=True)

    gravatar_email = models.EmailField(max_length=128, unique=False, blank=True,  null=True)

    def __unicode__(self):
        return self.github_login


class Repository(models.Model):
    name = models.CharField(max_length=250)
    fullname = models.CharField(max_length=250)
    tagline = models.CharField(max_length=250,null=True,blank=True)
    github_description = models.TextField( default="", verbose_name='Repository Description',null=True,blank=True)
    markdown = models.TextField( default="", verbose_name='Published Repo Info',null=True,blank=True)
    owner = models.ForeignKey('Patron',null=True,blank=True)
    private = models.NullBooleanField(default=False, null=True)
    created_at = models.DateTimeField(null=True,blank=True)
    updated_at = models.DateTimeField(null=True,blank=True)

    def __unicode__(self):
        return self.name


class Issue(models.Model):
    
    # # "url": "https://api.github.com/repos/claytantor/grailo/issues/4",
    # name = models.CharField(max_length=250, unique=False)
    github_api_url = models.CharField(max_length=250, unique=False)

    # "html_url": "https://github.com/claytantor/grailo/issues/4",
    github_html_url = models.CharField(max_length=250, unique=False)

    # "id": 8657138,
    github_id = models.BigIntegerField(unique=True, null=True)
    
    # "number": 4,
    github_issue_no = models.BigIntegerField(unique=False, null=True)
    
    # "title": "Message length check",  
    title = models.CharField(max_length=250, unique=False)

    json_body = models.TextField( default="", verbose_name='Issue JSON', unique=False, null=True)

    description = models.TextField( default="", verbose_name='Issue Description', unique=False, null=True)

    repository = models.ForeignKey('Repository',null=True,blank=True)

    status = models.CharField(max_length=16, unique=False)

    issue_user = models.ForeignKey('Patron',null=True,blank=True)

    created_at = models.DateTimeField(null=True,blank=True)

    updated_at = models.DateTimeField(null=True,blank=True)

    def __unicode__(self):
        return '{0} {1}'.format(self.github_id,self.title)





class Reward(models.Model):
    name = models.CharField(max_length=255, default="", verbose_name='Reward Name')
    amount = models.DecimalField(max_digits=8, decimal_places=2, default="", verbose_name="Minimum Amount")
    desc = models.TextField( default="", verbose_name='Reward Description')
    short_desc = models.CharField(max_length=255, default="", verbose_name='Short Reward Description')
    patron = models.ForeignKey('Patron',null=True,blank=True)
    issue = models.ForeignKey('Issue',null=True,blank=True)
    def __unicode__(self):
        return self.name

class Update(models.Model):
    created_at = models.DateTimeField(auto_now=True)
    subject = models.CharField(max_length=255)
    text = models.TextField()
    repository = models.ForeignKey('Repository',null=True,blank=True)
    read_status = models.IntegerField(default=0, null=True)
    def __unicode__(self):
        return self.subject

class Comment(models.Model):
    created_at = models.DateTimeField(auto_now=True)
    subject = models.CharField(max_length=255)
    text = models.TextField()
    patron = models.ForeignKey('Patron',null=True,blank=True)
    repository = models.ForeignKey('Repository',null=True,blank=True)
    def __unicode__(self):
        return self.subject

class Question(models.Model):
    created_at = models.DateTimeField(auto_now=True)
    subject = models.CharField(max_length=255)
    patron = models.ForeignKey('Patron',null=True,blank=True)
    text = models.TextField()

class CallbackMessage(models.Model):
    created_at = models.DateTimeField(auto_now=True)
    message = models.TextField()
    owner = models.ForeignKey('Patron',null=True,blank=True)
    processed_at = models.DateTimeField(null=True,blank=True)
    is_processed = models.NullBooleanField(default=False)
    def __unicode__(self):
        return 'message {0}'.format(self.id)

# {
#     "order": {
#         "id": "5RTQNACF",
#         "created_at": "2012-12-09T21:23:41-08:00",
#         "status": "completed",
#         "total_btc": {
#             "cents": 100000000,
#             "currency_iso": "BTC"
#         },
#         "total_native": {
#             "cents": 1253,
#             "currency_iso": "USD"
#         },
#         "custom": "order1234",
#         "receive_address": "1NhwPYPgoPwr5hynRAsto5ZgEcw1LzM3My",
#         "button": {
#             "type": "buy_now",
#             "name": "Alpaca Socks",
#             "description": "The ultimate in lightweight footwear",
#             "id": "5d37a3b61914d6d0ad15b5135d80c19f"
#         },
#         "transaction": {
#             "id": "514f18b7a5ea3d630a00000f",
#             "hash": "4a5e1e4baab89f3a32518a88c31bc87f618f76673e2cc77ab2127b7afdeda33b",
#             "confirmations": 0
#         },
#         "customer": {
#             "email": "coinbase@example.com",
#             "shipping_address": [
#                 "John Smith",
#                 "123 Main St.",
#                 "Springfield, OR 97477",
#                 "United States"
#             ]
#         },
#         "refund_address": "1HcmQZarSgNuGYz4r7ZkjYumiU4PujrNYk"
#     }
# }
class CoinOrder(models.Model):
     #"id": "5RTQNACF",
    external_id = models.CharField(max_length=128)
    status = models.CharField(max_length=36)
    total_coin_cents = models.BigIntegerField(default=0, verbose_name="Order BTC Amount")
    total_coin_currency_iso = models.CharField(max_length=3)
    receive_address = models.CharField(max_length=36)
    refund_address = models.CharField(max_length=36)
    button = models.ForeignKey('CoinbaseButton',null=True,blank=True)
    created_at = models.DateTimeField(null=True,blank=True)
    def __unicode__(self):
        return 'order: {0} button type: {1} issue: {2}'.format(self.external_id, self.button.type, self.button.issue.title)



#         "customer": {
#             "email": "coinbase@example.com",
#             "shipping_address": [
#                 "John Smith",
#                 "123 Main St.",
#                 "Springfield, OR 97477",
#                 "United States"
#             ]
#         },
class CoinCustomer(models.Model):
    email = models.CharField(max_length=64)
    order = models.ForeignKey(CoinOrder)
    addr_name = models.CharField(max_length=64)
    addr1 = models.CharField(max_length=64)
    addr2 = models.CharField(max_length=64)
    addr_contry = models.CharField(max_length=64)



#         "transaction": {
#             "id": "514f18b7a5ea3d630a00000f",
#             "hash": "4a5e1e4baab89f3a32518a88c31bc87f618f76673e2cc77ab2127b7afdeda33b",
#             "confirmations": 0
#         },
class CoinTransaction(models.Model):
    external_id =models.CharField(max_length=36)
    hash =models.CharField(max_length=64)
    order = models.ForeignKey(CoinOrder)
    confirmations = models.IntegerField(default=0)


class CoinbaseButton(models.Model):
    code = models.CharField(max_length=64)
    external_id = models.TextField()
    button_response = models.TextField()
    type = models.CharField(max_length=16,null=True,blank=True)

app/templates/beta_signup.html
{% load gitpatrontags %}
{% load markdown_deux_tags %}
{% load humanize %}
<!DOCTYPE html>
<html>
{% include 'head.html' %}
<script type="text/javascript">

$(document).ready(function() {



});

</script>
<body>
    {% include 'topbar.html' %}
    <div class="container gitpatron-top-container">
        <h1>Not In Beta Program</h1>
        <h2>{{ message }}</h2>
        <div class="alert alert-danger" role="alert">
          <strong>You are not in our BETA Program!</strong> We are still working on the website and its not quite ready for prime time. We are
            only working with key users who can help us improve our site until we are ready. We would love your help though so if you
            are interested in joining a select community who will have a very special relationship with the site then
            please <a href="http://eepurl.com/YxMjH">sign up for the BETA program</a> to
            participate in advance availability for gitpatron.
        </div>

    </div> <!-- /container -->
    {% include "footer.html" %}
</body>
</html>

app/templates/claimed_issue.html
{% load gitpatrontags %}
<!DOCTYPE html>
<html>
{% include 'head.html' %}
<script type="text/javascript">

$(document).ready(function() {

    $('button.fixed_issue').click(function (e) {
            $(this).find('span').show();
            $(this).find('span').toggleClass('glyphicon-refresh-animate');
            claimed_issue_id = $(this).data('claimed')
            $.ajax({
                url:"{{ settings.GITPATRON_APP_URL }}/fix_issue_ajax/"+claimed_issue_id+"/",
                success:function(result){
                    $("#fix_section").html(result);
                }
            });

        });

    });

</script>
<body>
    {% include 'topbar.html' %}
    <div class="container" style="margin-top: 60px;" id="repo_container">
        <div class="row" style="margin-top: 30px;">

            <div class="col-xs-12 col-sm-9">
                <h1>Claimed Issue</h1>
                <h4>Fix Payment Requested: {{ claimed.button.total_coin_cents|btc_cents }} BTC</h4>
                <div>
                    claimed by: <strong>{{ claimed.committer.user.username }}</strong>
                </div>
                {% if claimed.issue|is_repo_owner:request.user and not claimed.fixed  %}
                <div>
                    <div class="nav navbar-right" id="fix_section">
                    <button class="btn btn-primary fixed_issue" href="#" role="button" data-claimed="{{ claimed.id }}">
                        <span class="glyphicon glyphicon-refresh"
                      style="display: none"
                      id="issue_sync_icon"></span>&nbsp;Mark As Fixed</button>
                    </div>
                </div>
                <div>
                    <a class="coinbase-button"
                       data-code="{{ claimed.button.code }}"
                       data-button-text="Pay {{ claimed.committer.user.username }}"
                       data-button-style="buy_now_small"
                       href="https://coinbase.com/checkouts/{{ claimed.button.code }}">
                        Pay {{ claimed.committer.user.username }}</a>
                    <script src="https://coinbase.com/assets/button.js" type="text/javascript"></script>


                </div>
                {% else %}
                <div>
                    This issue is fixed.
                </div>
                {% endif %}

                <div>
                    See commit on github: <a href="{{ claimed.github_commit_id }}">{{ claimed.github_commit_id }}</a>
                </div>


            </div>
            <div class="col-xs-6 col-sm-3 sidebar-offcanvas" id="sidebar" role="navigation">
                {% include 'sidebar.html' %}
            </div><!--/span-->
        </div>




    </div> <!-- /container -->
</body>
</html>

app/templates/coin_info.html
<!DOCTYPE html>
<html>
{% include 'head.html' %}
<script type="text/javascript">

$(document).ready(function() {

});

</script>
<body>
    {% load markdown_deux_tags %}
    {% include 'topbar.html' %}
    <div class="container" style="margin-top: 45px;">
        <h1>COIN INFO</h1>
    </div>
</body>
</html>

app/templates/error.html
{% load gitpatrontags %}
{% load markdown_deux_tags %}
{% load humanize %}
<!DOCTYPE html>
<html>
{% include 'head.html' %}
<script type="text/javascript">

$(document).ready(function() {



});

</script>
<body>
    {% include 'topbar.html' %}
    <div class="container gitpatron-top-container">
        <h1>ERROR: {{ message }}</h1>
    </div> <!-- /container -->
    {% include "footer.html" %}
</body>
</html>

app/templates/fix_form_ajax.html
{% load gitpatrontags %}
{% if form.errors %}
<div class="form_errors bs-callout bs-callout-danger">
    <h4>Form Errors</h4>
    <p>Please fix the errors below and re-submit.</p>
    <ul>
    {% for error in form.git_commit_id.errors %}
        <li>git_commit_id:&nbsp;<strong>{{ error|escape }}</strong></li>
    {% endfor %}
    {% for error in form.message.errors %}
        <li>message:&nbsp;<strong>{{ error|escape }}</strong></li>
    {% endfor %}
    {% for error in form.min_amount.errors %}
        <li>min_amount:&nbsp;<strong>{{ error|escape }}</strong></li>
    {% endfor %}
    {% for error in form.issue_id.errors %}
        <li>issue_id:&nbsp;<strong>{{ error|escape }}</strong></li>
    {% endfor %}
    {% for error in form.type.errors %}
        <li>type:&nbsp;<strong>{{ error|escape }}</strong></li>
    {% endfor %}
    </ul>
</div>
{% endif %}

app/templates/head.html
<head>
    <meta charset="utf-8">
    <title>git patron</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="git patron">
    <meta name="author" content="Clay Graham">

    <!-- the styles -->
    <link href="{{STATIC_URL}}css/bootstrap.css" rel="stylesheet">
    <link href="{{STATIC_URL}}css/bootstrap-responsive.css" rel="stylesheet">
    <link href="{{STATIC_URL}}css/gitpatron.css" rel="stylesheet">
    <link href='https://fonts.googleapis.com/css?family=Ubuntu+Mono:400,700|Lusitana:400,700|Titillium+Web:400,700' rel='stylesheet' type='text/css'>
    <link href="{{STATIC_URL}}css/select2.css" rel="stylesheet"/>
    <!-- Load c3.css -->
    <link href="{{STATIC_URL}}css/c3.css" rel="stylesheet" type="text/css">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="{{ STATIC_URL }}js/html5shiv.js"></script>
    <![endif]-->

    <!-- Fav and touch icons -->
    <link rel="shortcut icon" href="{{STATIC_URL}}img/icon.png">
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="{{STATIC_URL}}ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="{{STATIC_URL}}ico/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="{{STATIC_URL}}ico/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="{{STATIC_URL}}ico/apple-touch-icon-57-precomposed.png">


    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>

    <script src="{{ STATIC_URL }}js/bootstrap.min.js"></script>
    <script src="{{ STATIC_URL }}js/mustache.js"></script>
    <script src="{{ STATIC_URL }}js/holder.js"></script>
    <script src="{{ STATIC_URL }}js/select2.min.js"></script>


    <!-- Load d3.js and c3.js -->
    <script src="{{ STATIC_URL }}js/d3.min.js" charset="utf-8"></script>
    <script src="{{ STATIC_URL }}js/c3.min.js"></script>
    <script src="{{ STATIC_URL }}js/gpcharts.js"></script>


</head>
<script type="text/javascript">
$(document).ready(function(){
    $('#github_login').click(function() {
        window.location.href="{% url 'login' %}";
    });
})
</script>

app/templates/issue_popup.html
{% load gitpatrontags %}
{% load markdown_deux_tags %}
{% load humanize %}
<!DOCTYPE html>
<html>
{% include 'head.html' %}
<script type="text/javascript">
$(document).ready(function() {


});
</script>
<body style="margin: 0px; padding: 0px; width: 100%; height: 100%; background-color: #aaaaaa;">
    <div class="container" id="issue_container" style="width: 100%; height: 100%;">
        <div style="width: 100%; margin-bottom: 5px;" class="text-center"><img src="{{ STATIC_URL }}img/gitpatron-widget-head.png"/></div>
        <div class="alert alert-info" role="alert">
            <strong>Share This Issue!</strong>&nbsp;Copy the HTML source below and place it it any web page to spread the word about funding this issue.
        </div>
        <textarea class="form-control" rows="5" style="margin-bottom: 30px;">
&lt;div id=&quot;issue_share_{{ issue_id }}&quot; style=&quot;margin-bottom:10px;padding:5px;width:200px;height:350px;display: inline-block;&quot;&gt;&lt;/div&gt;
&lt;script src=&quot;https://qa.gitpatron.com/widget/issue.js?issue_id={{ issue_id }}&quot; type=&quot;text/javascript&quot;&gt;&lt;/script&gt;
        </textarea>
    </div>
</body>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-52468228-1', 'auto');
  ga('require', 'displayfeatures');
  ga('send', 'pageview');

</script>
</html>

app/templates/pull_button_ajax.html
{% load gitpatrontags %}
{% if request.user and pull_request.status == 'open' and pull_request.issue_user.user == request.user and pull_request.fix_issue == None  %}
    <span id="pull_request_section_{{ pull_request.id }}">
        <div class="col-md-6">
           {% if issues|length > 0 %}
           <select class="form-control associate-issue-field" id="select_pull_{{ pull_request.id }}">
               {% for issue_fix in issues %}
                   {% if issue_fix|is_claimer:request.user and issue_fix|is_monetized_fixer:request.user == False %}
                    <option data-issue-owner="{{ issue_fix.repository.owner.user.username }}"
                            data-issue-id="{{ issue_fix.id }}"
                            data-repo-name="{{ issue_fix.repository.name }}"
                            data-github-issue="{{ issue_fix.github_issue_no }}">
                         #{{ issue_fix.github_issue_no }} {{ issue_fix.title }}
                    </option>
                   {% endif %}
               {% endfor %}
            </select>
            {% endif %}
        </div>
        <div class="col-md-6">
         <button class="btn btn-default btn-xs associate_pull" id="button_pull_{{ pull_request.id }}"
                 data-pull-request-id ="{{ pull_request.id  }}"
                 data-issue-owner="{{ pull_request.repository.owner.user.username }}"
                 data-repo-name="{{ pull_request.repository.name }}"
                 data-github-issue="{{ pull_request.github_issue_no }}">
            <span class="glyphicon glyphicon-refresh" style="display: none" id="issue_sync_icon"></span>
            &nbsp;Associate</button>
        </div>
    </span>
{% elif pull_request.fix_issue != None  %}
    {% if  pull_request.issue_user.user == request.user %}
        {% if pull_request.fix_issue|payment_status_filter == "monetized" %}
            MONETIZED
        {% elif pull_request.fix_issue|payment_status_filter == "fixed" %}
            FIXED
        {% elif pull_request.fix_issue|payment_status_filter == "claimed" and pull_request.fix_issue|is_funded %}
            {% if pull_request.fix_issue|is_funded and not pull_request.fix_issue|is_monetized_fix%}
                <span id="fixed_button_{{ pull_request.fix_issue.id }}">
                    <button class="btn btn-default btn-xs has-spinner monetize_fix" id="button_pull_monitize_{{ pull_request.id }}"
                         data-pull-request-id ="{{ pull_request.id  }}"
                         data-issue-owner="{{ pull_request.repository.owner.user.username }}"
                         data-repo-name="{{ pull_request.repository.name }}"
                         data-github-issue="{{ pull_request.github_issue_no }}">
                    <span class="glyphicon glyphicon-refresh" data-toggle="modal" data-target="#fix_modal"  style="display: none"></span>&nbsp;Monetize Fix</button>
                </span>
             {% elif pull_request.fix_issue|is_funded  %}
                MONETIZED FIX
            {% else %}
                NOT FUNDED
            {% endif %}
        {% endif %}
    {% else %}
        {% if pull_request.fix_issue|is_monetized_owner:request.user and pull_request.fix_issue|is_paid != True %}
            {% for button in pull_request.fix_issue.coinbasebutton_set.all %}
                {% if button.type == 'fix' and button.enabled %}
                    <a class="coinbase-button"
                       data-code="{{ button.code }}"
                       data-button-style="buy_now_small"
                       href="https://coinbase.com/checkouts/{{ button.code }}">
                        Pay Bitcoins</a>
                    <script src="https://coinbase.com/assets/button.js" type="text/javascript"></script>
                {% endif %}
            {% endfor %}&nbsp;
        {% elif pull_request.fix_issue|is_paid %}
            PAID
        {% else %}
            LINKED
        {% endif %}
    {% endif %}
{% endif %}
{{ button.code }}